package ee.ut.esi.group4.buildit.rental.domain.model;

public enum PHRStatus {
    PENDING, REJECTED, OPEN, CLOSED, APPROVED, CREATED, PO_CLOSED, PO_REJECTED, PO_OPEN, PO_CREATED, PO_PENDING_EXTENSION, PO_REJECT_EXTENSION, PO_UNMAPPED, INVOICED
}
